# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

TestApp::Application.load_tasks

namespace :ci do
  desc "Prepare for CI and run entire test suite"
  task :build => ['spec'] do
  end
end
